spring:
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
    quickfixjserver:
      enabled: true
  health:
    quickfixjserver:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjserver,health

logging:
  group:
    fix: quickfix.ThreadedSocketAcceptor, quickfixj.msg.incoming, quickfixj.msg,outgoing
    examples: org.quickfixj.examples

app:
  session:
    sender-comp-id: EXAMPLE-FIXLATEST-ACCEPTOR
    socket-acceptor-port: 9881

quickfixj:
  server:
    enabled: true
    auto-startup: true
    force-disconnect: false
    phase: 0
    jmx-enabled: true
    concurrent:
      enabled: true
      useDefaultExecutorFactory: true
    message-store-factory: memory
    log-factory: slf4j
    configString: |
      [default]
      BeginString=FIXT.1.1
      DefaultApplVerID=FIX.Latest
      UseDataDictionary=Y
      TransportDataDictionary=FIXT11.xml
      AppDataDictionary.FIX.Latest=FIXLatest.xml
      ConnectionType=acceptor
      TimeZone=Europe/London
      StartTime=00:00:00
      EndTime=00:00:00
      ResetOnLogon=Y
      ResetOnLogout=Y
      ResetOnDisconnect=Y
      ValidateUnorderedFields=Y
      ValidateUserDefinedFields=Y
      CheckLatency=Y
      HeartBtInt=30
      PersistMessages=N
      SenderCompID=EXEC
      TargetCompID=BANZAI
      UseDataDictionary=Y
      DefaultMarketPrice=12.30
      FileLogPath=logs-server
      SocketAcceptPort=9881
      SenderCompID=${app.session.sender-comp-id}
      SocketAcceptorPort=${socket-acceptor-port}
      
      #SSL
      SocketUseSSL=N

      [session]
      TargetCompID=EXAMPLE-FIXLATEST-INITIATOR
